-- Run this in Snowflake once to set up Retrosheet events tables.

-- 1. Create the database and schema
CREATE DATABASE IF NOT EXISTS BASEBALL;
CREATE SCHEMA IF NOT EXISTS BASEBALL.HISTORICAL;

-- Set session context so all subsequent statements resolve correctly
USE DATABASE BASEBALL;
USE SCHEMA HISTORICAL;

-- Retrosheet Events via pybaseball
CREATE TABLE IF NOT EXISTS BASEBALL.HISTORICAL.RETROSHEET_EVENTS (
    -- Identifiers
    DATE_DBLHEAD                INT,
    SEASON                      FLOAT,
    
    -- Game info
    TEAM_V                      VARCHAR(3),
    LEAGUE_V                    VARCHAR(2),
    TEAM_H                      VARCHAR(3),
    LEAGUE_H                    VARCHAR(2),
    RUNS_V                      FLOAT,
    RUNS_H                      FLOAT,
    RUN_TOTAL                   FLOAT,
    RUN_DIFF                    FLOAT,
    DURATION                    FLOAT,
    HOME_VICTORY                INTEGER,
    
    -- Visiting team stats
    AB_V                        FLOAT,
    H_V                         FLOAT,
    X2B_V                       FLOAT,
    X3B_V                       FLOAT,
    HR_V                        FLOAT,
    RBI_V                       FLOAT,
    SAC_HITS_V                  FLOAT,
    SAC_FLIES_V                 FLOAT,
    HBP_V                       FLOAT,
    BB_V                        FLOAT,
    IBB_V                       FLOAT,
    K_V                         FLOAT,
    SB_V                        FLOAT,
    CS_V                        FLOAT,
    GDP_V                       FLOAT,
    CI_V                        FLOAT,
    LOB_V                       FLOAT,
    NUM_PITCHERS_V              FLOAT,
    IER_V                       FLOAT,
    ER_V                        FLOAT,
    WP_V                        FLOAT,
    BALKS_V                     FLOAT,
    PO_V                        FLOAT,
    ASSISTS_V                   FLOAT,
    ERR_V                       FLOAT,
    PB_V                        FLOAT,
    X2P_V                       FLOAT,
    X3P_V                       FLOAT,
    STARTING_PITCHER_ID_V       VARCHAR(10),
    STARTING_PITCHER_NAME_V     VARCHAR(100),
    BATTER1_ID_V                VARCHAR(10),
    BATTER2_ID_V                VARCHAR(10),
    BATTER3_ID_V                VARCHAR(10),
    BATTER4_ID_V                VARCHAR(10),
    BATTER5_ID_V                VARCHAR(10),
    BATTER6_ID_V                VARCHAR(10),
    BATTER7_ID_V                VARCHAR(10),
    BATTER8_ID_V                VARCHAR(10),
    BATTER9_ID_V                VARCHAR(10),
    BATTER1_NAME_V              VARCHAR(100),
    BATTER2_NAME_V              VARCHAR(100),
    BATTER3_NAME_V              VARCHAR(100),
    BATTER4_NAME_V              VARCHAR(100),
    BATTER5_NAME_V              VARCHAR(100),
    BATTER6_NAME_V              VARCHAR(100),
    BATTER7_NAME_V              VARCHAR(100),
    BATTER8_NAME_V              VARCHAR(100),
    BATTER9_NAME_V              VARCHAR(100),
    BATTER1_POS_V               FLOAT,
    BATTER2_POS_V               FLOAT,
    BATTER3_POS_V               FLOAT,
    BATTER4_POS_V               FLOAT,
    BATTER5_POS_V               FLOAT,
    BATTER6_POS_V               FLOAT,
    BATTER7_POS_V               FLOAT,
    BATTER8_POS_V               FLOAT,
    BATTER9_POS_V               FLOAT,
    MANAGER_V                   VARCHAR(100),
    
    -- Home team stats
    AB_H                        FLOAT,
    H_H                         FLOAT,
    X2B_H                       FLOAT,
    X3B_H                       FLOAT,
    HR_H                        FLOAT,
    RBI_H                       FLOAT,
    SAC_HITS_H                  FLOAT,
    SAC_FLIES_H                 FLOAT,
    HBP_H                       FLOAT,
    BB_H                        FLOAT,
    IBB_H                       FLOAT,
    K_H                         FLOAT,
    SB_H                        FLOAT,
    CS_H                        FLOAT,
    GDP_H                       FLOAT,
    CI_H                        FLOAT,
    LOB_H                       FLOAT,
    NUM_PITCHERS_H              FLOAT,
    IER_H                       FLOAT,
    ER_H                        FLOAT,
    WP_H                        FLOAT,
    BALKS_H                     FLOAT,
    PO_H                        FLOAT,
    ASSISTS_H                   FLOAT,
    ERR_H                       FLOAT,
    PB_H                        FLOAT,
    X2P_H                       FLOAT,
    X3P_H                       FLOAT,
    STARTING_PITCHER_ID_H       VARCHAR(10),
    STARTING_PITCHER_NAME_H     VARCHAR(100),
    BATTER1_ID_H                VARCHAR(10),
    BATTER2_ID_H                VARCHAR(10),
    BATTER3_ID_H                VARCHAR(10),
    BATTER4_ID_H                VARCHAR(10),
    BATTER5_ID_H                VARCHAR(10),
    BATTER6_ID_H                VARCHAR(10),
    BATTER7_ID_H                VARCHAR(10),
    BATTER8_ID_H                VARCHAR(10),
    BATTER9_ID_H                VARCHAR(10),
    BATTER1_NAME_H              VARCHAR(100),
    BATTER2_NAME_H              VARCHAR(100),
    BATTER3_NAME_H              VARCHAR(100),
    BATTER4_NAME_H              VARCHAR(100),
    BATTER5_NAME_H              VARCHAR(100),
    BATTER6_NAME_H              VARCHAR(100),
    BATTER7_NAME_H              VARCHAR(100),
    BATTER8_NAME_H              VARCHAR(100),
    BATTER9_NAME_H              VARCHAR(100),
    BATTER1_POS_H               FLOAT,
    BATTER2_POS_H               FLOAT,
    BATTER3_POS_H               FLOAT,
    BATTER4_POS_H               FLOAT,
    BATTER5_POS_H               FLOAT,
    BATTER6_POS_H               FLOAT,
    BATTER7_POS_H               FLOAT,
    BATTER8_POS_H               FLOAT,
    BATTER9_POS_H               FLOAT,
    MANAGER_H                   VARCHAR(100),
    
    -- Rolling window stats (home team)
    BATAVG_162_H        FLOAT,
    BATAVG_90_H         FLOAT,
    BATAVG_30_H         FLOAT,
    OBP_162_H           FLOAT,
    OBP_90_H            FLOAT,
    OBP_30_H            FLOAT,
    SLG_162_H           FLOAT,
    SLG_90_H            FLOAT,
    SLG_30_H            FLOAT,
    OBS_162_H           FLOAT,
    OBS_90_H            FLOAT,
    OBS_30_H            FLOAT,
    SB_162_H            FLOAT,
    SB_90_H             FLOAT,
    SB_30_H             FLOAT,
    CS_162_H            FLOAT,
    CS_90_H             FLOAT,
    CS_30_H             FLOAT,
    ERR_162_H           FLOAT,
    ERR_90_H            FLOAT,
    ERR_30_H            FLOAT,
    
    -- Rolling window stats (visitor team)
    BATAVG_162_V        FLOAT,
    BATAVG_90_V         FLOAT,
    BATAVG_30_V         FLOAT,
    OBP_162_V           FLOAT,
    OBP_90_V            FLOAT,
    OBP_30_V            FLOAT,
    SLG_162_V           FLOAT,
    SLG_90_V            FLOAT,
    SLG_30_V            FLOAT,
    OBS_162_V           FLOAT,
    OBS_90_V            FLOAT,
    OBS_30_V            FLOAT,
    SB_162_V            FLOAT,
    SB_90_V             FLOAT,
    SB_30_V             FLOAT,
    CS_162_V            FLOAT,
    CS_90_V             FLOAT,
    CS_30_V             FLOAT,
    ERR_162_V           FLOAT,
    ERR_90_V            FLOAT,
    ERR_30_V            FLOAT,
    
    -- Pipeline metadata
    _loaded_at                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _source                     VARCHAR(50) DEFAULT 'pybaseball_retrosheet_events'
);